FROM python:3.8-slim as builder

RUN python -m venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"

WORKDIR /app

COPY . /app

RUN pip install ./stac_fastapi/types && \
    pip install ./stac_fastapi/api && \
    pip install ./stac_fastapi/extensions && \
    pip install ./stac_fastapi/pgstac[server]


FROM python:3.8-slim as pgstac

ENV CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

COPY --from=builder /opt/venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y wget
RUN apt-get install -y postgresql-client
COPY entrypoint.sh .
# Make the script executable
RUN chmod +x entrypoint.sh
RUN pwd
RUN ls
# Download the schema file from the provided URL wget -O /tmp/pgstac.sql https://raw.githubusercontent.com/stac-utils/pgstac/main/src/pgstac/migrations/pgstac.0.7.1.sql

RUN wget -O /tmp/pgstac.sql https://raw.githubusercontent.com/stac-utils/pgstac/main/src/pgstac/migrations/pgstac.0.7.1.sql

# Set the entrypoint for the container to the script
ENTRYPOINT ["./entrypoint.sh"]
CMD ["uvicorn", "stac_fastapi.pgstac.app:app", "--host", "0.0.0.0", "--port", "8082"]
