name: Build and push Docker image for pgstac - prod environment

permissions:
  contents: read
on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  docker-build-push-prod:
    runs-on: ubuntu-latest
    environment: PROD_ENVIRONMENT

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set Short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short=7 $GITHUB_SHA)" >> $GITHUB_ENV
      - name: echo Short SHA
        run: echo $SHORT_SHA
      # - name: Log in to the Container registry
      #   uses: docker/login-action@v2.1.0
      #   with:
      #     registry: ${{ vars.DOCKER_REGISTRY_URL}}
      #     username: ${{ secrets.DOCKER_REGISTRY_USER }}
      #     password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v4.0.0
      #   with:
      #     context: .
      #     file: docker/Dockerfile.pgstac
      #     cache-from: type=registry,ref=${{ vars.DOCKER_REGISTRY_URL }}/stac-fastapi:cache
      #     cache-to: type=registry,ref=${{ vars.DOCKER_REGISTRY_URL }}/stac-fastapi:cache,mode=max
      #     push: true
      #     tags: ${{ vars.DOCKER_REGISTRY_URL }}/stac-fastapi:${{ env.SHORT_SHA }}
